modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/Aar0w/Create-Recipe-Hooks/issues"

[[mods]]
    modId = "createrecipehooks"
    version = "${file.jarVersion}"
    displayName = "Create Recipe Hooks"
    authors = "Aarow"
    logoFile = "crhlogo.png"
    description = '''
        Provides a unified API for listening to Create (and addon) recipe completions.
        Intended for use by FTB Quests, KubeJS, and other integration mods.
    '''

[[dependencies.createrecipehooks]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.createrecipehooks]]
    modId = "create"
    mandatory = true
    versionRange = "[6.0.8,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.createrecipehooks]]
    modId = "kubejs"
    mandatory = false
    versionRange = "[2001.6.5,)"
    ordering = "AFTER"
    side = "BOTH"
